/**
 * Quantum Fluidity — theme template.
 *
 * buildTheme(palette) returns a complete VS Code color theme object.
 * All four variants share this structure; only the palette differs.
 */

const alpha = (hex, a) => `${hex}${a}`;

export function buildTheme(p) {
  const dark = p.type === 'dark';
  // Floating surfaces (menus, widgets, notifications): one step up in dark,
  // pure white in light themes.
  const float = dark ? p.bgAlt : '#FFFFFF';
  // Text placed on violet/accent fills (badges, buttons, debug status bar).
  const onViolet = dark ? p.bg : '#FFFFFF';

  return {
    name: p.name,
    type: p.type,
    semanticHighlighting: true,
    semanticTokenColors: {
      class: { foreground: p.green, bold: true },
      interface: { foreground: p.amber, italic: true },
      function: { foreground: p.accent, italic: true },
      method: { foreground: p.accent, italic: true },
      'variable.readonly': { foreground: p.fg, bold: true },
      'variable.defaultLibrary': { foreground: p.accent, bold: true },
      property: { foreground: p.fg },
      parameter: { foreground: p.accent, italic: true },
      enum: { foreground: p.green, bold: true },
      enumMember: { foreground: p.amber },
      type: { foreground: p.green },
      typeParameter: { foreground: p.green, italic: true },
      struct: { foreground: p.green, bold: true },
      namespace: { foreground: p.fg },
      decorator: { foreground: p.accent, italic: true },
      macro: { foreground: p.violet },
      event: { foreground: p.amber },
      'property.readonly': { foreground: p.fg, bold: true },
      '*.deprecated': { strikethrough: true },
    },
    colors: {
      'editor.background': p.bg,
      'editor.foreground': p.fg,
      'activityBar.background': p.bgSide,
      'activityBar.foreground': p.fg,
      'activityBar.inactiveForeground': alpha(p.fg, '80'),
      'activityBarBadge.background': p.violet,
      'activityBarBadge.foreground': onViolet,
      'activityBar.border': p.container,
      'sideBar.background': p.bgSide,
      'sideBar.foreground': p.fg,
      'sideBar.border': p.container,
      'sideBarSectionHeader.background': p.bgAlt,
      'sideBarSectionHeader.foreground': p.fg,
      'terminal.background': p.bgSide,
      'terminal.foreground': p.fg,
      'terminalCursor.foreground': p.accent,
      'terminal.ansiBlack': p.terminal.black,
      'terminal.ansiRed': p.terminal.red,
      'terminal.ansiGreen': p.terminal.green,
      'terminal.ansiYellow': p.terminal.yellow,
      'terminal.ansiBlue': p.terminal.blue,
      'terminal.ansiMagenta': p.terminal.magenta,
      'terminal.ansiCyan': p.terminal.cyan,
      'terminal.ansiWhite': p.terminal.white,
      'terminal.ansiBrightBlack': p.terminal.brightBlack,
      'terminal.ansiBrightRed': p.terminal.brightRed,
      'terminal.ansiBrightGreen': p.terminal.brightGreen,
      'terminal.ansiBrightYellow': p.terminal.brightYellow,
      'terminal.ansiBrightBlue': p.terminal.brightBlue,
      'terminal.ansiBrightMagenta': p.terminal.brightMagenta,
      'terminal.ansiBrightCyan': p.terminal.brightCyan,
      'terminal.ansiBrightWhite': p.terminal.brightWhite,
      'editor.selectionBackground': alpha(p.accent, '2E'),
      'editor.selectionHighlightBackground': alpha(p.accent, '1A'),
      'editor.wordHighlightBackground': alpha(p.violet, '26'),
      'editor.lineHighlightBackground': p.bgAlt,
      'editorLineNumber.foreground': alpha(p.fg, '40'),
      'editorLineNumber.activeForeground': p.accent,
      'editorCursor.foreground': p.accent,
      'editorIndentGuide.background': alpha(p.container, '80'),
      'editorIndentGuide.activeBackground': dark ? p.container : p.containerHover,
      'list.activeSelectionBackground': p.container,
      'list.activeSelectionForeground': p.fg,
      'list.inactiveSelectionBackground': alpha(p.container, '80'),
      'list.inactiveSelectionForeground': p.fg,
      'list.hoverBackground': p.bgAlt,
      'list.hoverForeground': p.fg,
      'list.focusBackground': p.container,
      'list.focusForeground': p.accent,
      'list.highlightForeground': p.accent,
      focusBorder: p.accent,
      'badge.background': p.violet,
      'badge.foreground': onViolet,
      'panel.background': p.bgSide,
      'panel.border': p.container,
      'panelTitle.activeBorder': p.accent,
      'panelTitle.activeForeground': p.fg,
      'panelTitle.inactiveForeground': alpha(p.fg, '80'),
      'tab.activeBackground': p.bg,
      'tab.activeForeground': p.fg,
      'tab.activeBorderTop': p.accent,
      'tab.activeBorder': alpha(p.accent, '00'),
      'tab.inactiveBackground': p.bgTop,
      'tab.inactiveForeground': alpha(p.fg, '80'),
      'tab.border': p.container,
      'editorGroupHeader.tabsBackground': p.bgTop,
      'editorGroup.border': p.container,
      'titleBar.activeBackground': p.bgTop,
      'titleBar.activeForeground': p.fg,
      'titleBar.inactiveBackground': p.bgTop,
      'titleBar.inactiveForeground': alpha(p.fg, '80'),
      'statusBar.background': p.container,
      'statusBar.foreground': p.fg,
      'statusBar.border': p.container,
      'statusBar.debuggingBackground': p.violet,
      'statusBar.debuggingForeground': onViolet,
      'statusBar.noFolderBackground': p.bg,
      'button.background': p.violet,
      'button.foreground': onViolet,
      'button.hoverBackground': p.violetBright,
      'button.secondaryBackground': p.container,
      'button.secondaryForeground': p.fg,
      'button.secondaryHoverBackground': p.containerHover,
      'input.background': float,
      'input.foreground': p.fg,
      'input.border': p.container,
      'inputOption.activeBorder': p.accent,
      'inputValidation.errorBackground': alpha(p.pink, dark ? '40' : '20'),
      'inputValidation.errorBorder': p.pink,
      'dropdown.background': float,
      'dropdown.foreground': p.fg,
      'dropdown.border': p.container,
      'editorWidget.background': float,
      'editorWidget.border': p.container,
      'editorSuggestWidget.background': float,
      'editorSuggestWidget.border': p.container,
      'editorSuggestWidget.selectedBackground': p.container,
      'diffEditor.insertedTextBackground': alpha(p.green, '20'),
      'diffEditor.removedTextBackground': alpha(p.pink, '20'),
      'editorGutter.addedBackground': p.green,
      'editorGutter.modifiedBackground': p.accent,
      'editorGutter.deletedBackground': p.pink,
      'scrollbarSlider.background': alpha(p.container, '80'),
      'scrollbarSlider.hoverBackground': dark ? p.container : p.containerHover,
      'scrollbarSlider.activeBackground': alpha(p.accent, '80'),
      'scrollbar.shadow': dark ? p.bg : p.container,
      'editorBracketHighlight.foreground1': p.brackets[0],
      'editorBracketHighlight.foreground2': p.brackets[1],
      'editorBracketHighlight.foreground3': p.brackets[2],
      'editorBracketHighlight.foreground4': p.brackets[3],
      'editorBracketHighlight.foreground5': p.brackets[4],
      'editorBracketHighlight.foreground6': p.brackets[5],
      'editorBracketHighlight.unexpectedBracket.foreground': p.pink,
      'editorOverviewRuler.border': p.container,
      'editorOverviewRuler.findMatchForeground': alpha(p.accent, '80'),
      'editorOverviewRuler.errorForeground': p.pink,
      'editorOverviewRuler.warningForeground': p.amber,
      'editorOverviewRuler.infoForeground': p.accent,
      'editorOverviewRuler.bracketMatchForeground': p.violet,
      'minimap.findMatchHighlight': p.accent,
      'minimap.selectionHighlight': p.container,
      'minimap.errorHighlight': p.pink,
      'minimap.warningHighlight': p.amber,
      'minimapGutter.addedBackground': p.green,
      'minimapGutter.modifiedBackground': p.accent,
      'minimapGutter.deletedBackground': p.pink,
      'editorError.foreground': p.pink,
      'editorWarning.foreground': p.amber,
      'editorInfo.foreground': p.accent,
      'editorHint.foreground': p.green,
      'problemsErrorIcon.foreground': p.pink,
      'problemsWarningIcon.foreground': p.amber,
      'problemsInfoIcon.foreground': p.accent,
      'editorWhitespace.foreground': p.container,
      'editorRuler.foreground': p.container,
      'editorLink.activeForeground': p.accent,
      'editor.findMatchBackground': alpha(p.accent, '40'),
      'editor.findMatchHighlightBackground': alpha(p.accent, '1F'),
      'editor.findRangeHighlightBackground': alpha(p.container, '80'),
      'editor.rangeHighlightBackground': alpha(p.container, '80'),
      'editor.hoverHighlightBackground': alpha(p.container, '80'),
      'editor.wordHighlightStrongBackground': alpha(p.green, '26'),
      'selection.background': alpha(p.accent, '2E'),
      'terminal.selectionBackground': alpha(p.accent, '2E'),
      'editorBracketMatch.background': alpha(p.accent, '26'),
      'editorBracketMatch.border': p.accent,
      'editorHoverWidget.background': float,
      'editorHoverWidget.foreground': p.fg,
      'editorHoverWidget.border': p.container,
      'editorHoverWidget.statusBarBackground': p.bg,
      'peekView.border': p.accent,
      'peekViewEditor.background': float,
      'peekViewEditor.matchHighlightBackground': alpha(p.accent, '40'),
      'peekViewResult.background': p.bg,
      'peekViewResult.fileForeground': p.fg,
      'peekViewResult.lineForeground': alpha(p.fg, '80'),
      'peekViewResult.matchHighlightBackground': alpha(p.accent, '40'),
      'peekViewResult.selectionBackground': p.container,
      'peekViewResult.selectionForeground': p.accent,
      'peekViewTitle.background': p.bg,
      'peekViewTitleDescription.foreground': alpha(p.fg, '80'),
      'peekViewTitleLabel.foreground': p.accent,
      'notifications.background': float,
      'notifications.foreground': p.fg,
      'notifications.border': p.container,
      'notificationCenterHeader.background': p.bg,
      'notificationCenterHeader.foreground': p.fg,
      'notificationToast.border': p.container,
      'notificationsErrorIcon.foreground': p.pink,
      'notificationsWarningIcon.foreground': p.amber,
      'notificationsInfoIcon.foreground': p.accent,
      'notificationLink.foreground': p.accent,
      'menu.background': float,
      'menu.foreground': p.fg,
      'menu.border': p.container,
      'menu.selectionBackground': p.container,
      'menu.selectionForeground': p.accent,
      'menu.separatorBackground': p.container,
      'menubar.selectionBackground': p.container,
      'menubar.selectionForeground': p.fg,
      'breadcrumb.foreground': alpha(p.fg, '80'),
      'breadcrumb.focusForeground': p.fg,
      'breadcrumb.activeSelectionForeground': p.accent,
      'breadcrumbPicker.background': float,
      'quickInput.background': float,
      'quickInput.foreground': p.fg,
      'quickInputList.focusBackground': p.container,
      'quickInputList.focusForeground': p.accent,
      'quickInputTitle.background': p.bg,
      'pickerGroup.foreground': p.accent,
      'pickerGroup.border': p.container,
      'commandCenter.background': float,
      'commandCenter.foreground': p.fg,
      'commandCenter.border': p.container,
      'commandCenter.activeBackground': p.container,
      'commandCenter.activeForeground': p.accent,
      'commandCenter.inactiveForeground': alpha(p.fg, '80'),
      'gitDecoration.modifiedResourceForeground': p.accent,
      'gitDecoration.deletedResourceForeground': p.pink,
      'gitDecoration.untrackedResourceForeground': p.green,
      'gitDecoration.ignoredResourceForeground': alpha(p.fg, '40'),
      'gitDecoration.conflictingResourceForeground': p.amber,
      'gitDecoration.addedResourceForeground': p.green,
      'gitDecoration.stageModifiedResourceForeground': p.violet,
      'gitDecoration.stageDeletedResourceForeground': p.pinkBright,
      'gitDecoration.submoduleResourceForeground': p.violet,
      'merge.currentHeaderBackground': alpha(p.accent, '40'),
      'merge.currentContentBackground': alpha(p.accent, '20'),
      'merge.incomingHeaderBackground': alpha(p.violet, '40'),
      'merge.incomingContentBackground': alpha(p.violet, '20'),
      'merge.border': p.container,
      'editorStickyScroll.background': p.bgAlt,
      'editorStickyScrollHover.background': p.container,
      'sideBarTitle.foreground': p.fg,
      'tree.indentGuidesStroke': p.container,
      'textLink.foreground': p.accent,
      'textLink.activeForeground': p.accentBright,
      'textPreformat.foreground': p.amber,
      'textBlockQuote.background': float,
      'textBlockQuote.border': p.accent,
      'textCodeBlock.background': float,
      'textSeparator.foreground': p.container,
      errorForeground: p.pink,
      descriptionForeground: alpha(p.fg, '80'),
      'icon.foreground': p.fg,
      'widget.shadow': dark ? '#00000080' : '#00000020',
      'widget.border': p.container,
      'progressBar.background': p.accent,
      'toolbar.hoverBackground': p.container,
      'toolbar.activeBackground': p.container,
      'keybindingLabel.background': p.container,
      'keybindingLabel.foreground': p.fg,
      'keybindingLabel.border': p.container,
      'keybindingLabel.bottomBorder': p.container,
      'settings.headerForeground': p.fg,
      'settings.modifiedItemIndicator': p.accent,
      'settings.dropdownBackground': float,
      'settings.checkboxBackground': float,
      'settings.textInputBackground': float,
      'settings.numberInputBackground': float,
      'statusBarItem.remoteBackground': p.violet,
      'statusBarItem.remoteForeground': onViolet,
      'statusBarItem.errorBackground': p.pink,
      'statusBarItem.errorForeground': dark ? p.fg : '#FFFFFF',
      'statusBarItem.warningBackground': p.amber,
      'statusBarItem.warningForeground': dark ? p.bg : '#FFFFFF',
      'statusBarItem.prominentBackground': p.container,
      'statusBarItem.hoverBackground': p.containerHover,
      'debugIcon.breakpointForeground': p.pink,
      'debugToolBar.background': float,
      'debugToolBar.border': p.container,
      'editor.stackFrameHighlightBackground': alpha(p.amber, '20'),
      'editor.focusedStackFrameHighlightBackground': alpha(p.green, '20'),
      'testing.iconPassed': p.green,
      'testing.iconFailed': p.pink,
      'testing.iconQueued': p.amber,
      'testing.iconSkipped': p.violet,
      'editorGhostText.foreground': p.ghost,
      'editorInlayHint.foreground': p.inlay,
      'editorInlayHint.background': float,
      'editorInlayHint.typeForeground': p.green,
      'editorInlayHint.typeBackground': float,
      'editorInlayHint.parameterForeground': p.amber,
      'editorInlayHint.parameterBackground': float,
    },
    tokenColors: [
      {
        name: 'Comment',
        scope: ['comment', 'punctuation.definition.comment'],
        settings: { fontStyle: 'italic', foreground: p.comment },
      },
      {
        name: 'Variables',
        scope: ['variable', 'string constant.other.placeholder'],
        settings: { foreground: p.fg },
      },
      {
        name: 'Colors',
        scope: ['constant.other.color'],
        settings: { foreground: p.accent },
      },
      {
        name: 'Invalid',
        scope: ['invalid', 'invalid.illegal'],
        settings: { foreground: p.pink },
      },
      {
        name: 'Keyword, Storage',
        scope: ['keyword', 'storage.type', 'storage.modifier'],
        settings: { foreground: p.violet, fontStyle: 'bold' },
      },
      {
        name: 'Operator, Misc',
        scope: [
          'keyword.control',
          'constant.other.color',
          'punctuation',
          'meta.tag',
          'punctuation.definition.tag',
          'punctuation.separator.inheritance.php',
          'punctuation.definition.tag.html',
          'punctuation.definition.tag.begin.html',
          'punctuation.definition.tag.end.html',
          'punctuation.section.embedded',
          'keyword.other.template',
          'keyword.other.substitution',
        ],
        settings: { foreground: p.violet },
      },
      {
        name: 'Tag',
        scope: ['entity.name.tag', 'meta.tag.sgml', 'markup.deleted.git_gutter'],
        settings: { foreground: p.pink },
      },
      {
        name: 'Function, Special Method',
        scope: [
          'entity.name.function',
          'meta.function-call',
          'variable.function',
          'support.function',
          'keyword.other.special-method',
        ],
        settings: { foreground: p.accent },
      },
      {
        name: 'Block Level Variables',
        scope: ['meta.block variable.other'],
        settings: { foreground: p.fg },
      },
      {
        name: 'Other Variable, String Link',
        scope: ['support.other.variable', 'string.other.link'],
        settings: { foreground: p.fg },
      },
      {
        name: 'Number, Constant, Function Argument, Tag Attribute, Embedded',
        scope: [
          'constant.numeric',
          'constant.language',
          'support.constant',
          'constant.character',
          'constant.escape',
          'variable.parameter',
          'keyword.other.unit',
          'keyword.other',
        ],
        settings: { foreground: p.amber },
      },
      {
        name: 'String, Symbols, Inherited Class, Markup Heading',
        scope: [
          'string',
          'constant.other.symbol',
          'constant.other.key',
          'entity.other.inherited-class',
          'markup.heading',
          'markup.inserted.git_gutter',
          'meta.group.braces.curly constant.other.object.key.js string.unquoted.label.js',
        ],
        settings: { foreground: p.pink },
      },
      {
        name: 'Class, Support',
        scope: [
          'entity.name',
          'support.class',
          'support.other.namespace.use.php',
          'meta.use.php',
          'support.other.namespace.php',
          'markup.changed.git_gutter',
          'support.type.sys-types',
        ],
        settings: { foreground: p.green, fontStyle: 'bold' },
      },
      {
        name: 'Entity Types',
        scope: ['support.type'],
        settings: { foreground: p.violet },
      },
      {
        name: 'CSS Class and Support',
        scope: [
          'source.css support.type.property-name',
          'source.sass support.type.property-name',
          'source.scss support.type.property-name',
          'source.less support.type.property-name',
          'source.stylus support.type.property-name',
          'source.postcss support.type.property-name',
        ],
        settings: { foreground: p.accent },
      },
      {
        name: 'Sub-methods',
        scope: [
          'entity.name.module.js',
          'variable.import.parameter.js',
          'variable.other.class.js',
        ],
        settings: { foreground: p.fg },
      },
      {
        name: 'Language methods',
        scope: ['variable.language'],
        settings: { fontStyle: 'italic', foreground: p.violet },
      },
      {
        name: 'entity.name.method.js',
        scope: ['entity.name.method.js'],
        settings: { fontStyle: 'italic', foreground: p.accent },
      },
      {
        name: 'meta.method.js',
        scope: [
          'meta.class-method.js entity.name.function.js',
          'variable.function.constructor',
        ],
        settings: { foreground: p.accent },
      },
      {
        name: 'Attributes',
        scope: ['entity.other.attribute-name'],
        settings: { foreground: p.violet },
      },
      {
        name: 'HTML Attributes',
        scope: [
          'text.html.basic entity.other.attribute-name.html',
          'text.html.basic entity.other.attribute-name',
        ],
        settings: { fontStyle: 'italic', foreground: p.pink },
      },
      {
        name: 'CSS Classes',
        scope: ['entity.other.attribute-name.class'],
        settings: { foreground: p.accent },
      },
      {
        name: "CSS ID's",
        scope: ['source.sass keyword.control'],
        settings: { foreground: p.accent },
      },
      {
        name: 'Inserted',
        scope: ['markup.inserted'],
        settings: { foreground: p.green },
      },
      {
        name: 'Deleted',
        scope: ['markup.deleted'],
        settings: { foreground: p.pink },
      },
      {
        name: 'Changed',
        scope: ['markup.changed'],
        settings: { foreground: p.amber },
      },
      {
        name: 'Regular Expressions',
        scope: ['string.regexp'],
        settings: { foreground: p.accent },
      },
      {
        name: 'Escape Characters',
        scope: ['constant.character.escape'],
        settings: { foreground: p.accent },
      },
      {
        name: 'URL',
        scope: ['*url*', '*link*', '*uri*'],
        settings: { fontStyle: 'underline' },
      },
      {
        name: 'Decorators',
        scope: [
          'tag.decorator.js entity.name.tag.js',
          'tag.decorator.js punctuation.definition.tag.js',
        ],
        settings: { fontStyle: 'italic', foreground: p.accent },
      },
      {
        name: 'ES7 Bind Operator',
        scope: ['source.js constant.other.object.key.js string.unquoted.label.js'],
        settings: { fontStyle: 'italic', foreground: p.violet },
      },
      {
        name: 'JSON Key - Level 0',
        scope: ['source.json meta.structure.dictionary.json support.type.property-name.json'],
        settings: { foreground: p.accent },
      },
      {
        name: 'JSON Key - Level 1',
        scope: [
          'source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json',
        ],
        settings: { foreground: p.violet },
      },
      {
        name: 'JSON Key - Level 2',
        scope: [
          'source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json',
        ],
        settings: { foreground: p.fg },
      },
      {
        name: 'Markdown - Plain',
        scope: ['text.html.markdown', 'punctuation.definition.list_item.markdown'],
        settings: { foreground: p.fg },
      },
      {
        name: 'Markdown - Markup Raw Inline',
        scope: ['text.html.markdown markup.inline.raw.markdown'],
        settings: { foreground: p.violet },
      },
      {
        name: 'Markdown - Markup Raw Inline Punctuation',
        scope: [
          'text.html.markdown markup.inline.raw.markdown punctuation.definition.raw.markdown',
        ],
        settings: { foreground: p.accent },
      },
      {
        name: 'Markdown - Heading',
        scope: [
          'markdown.heading',
          'markup.heading | markup.heading entity.name',
          'markup.heading.markdown punctuation.definition.heading.markdown',
        ],
        settings: { foreground: p.accent },
      },
      {
        name: 'Markup - Italic',
        scope: ['markup.italic'],
        settings: { fontStyle: 'italic', foreground: p.violet },
      },
      {
        name: 'Markup - Bold',
        scope: ['markup.bold', 'markup.bold string'],
        settings: { fontStyle: 'bold', foreground: p.violet },
      },
      {
        name: 'Markup - Bold-Italic',
        scope: [
          'markup.bold markup.italic',
          'markup.italic markup.bold',
          'markup.quote markup.bold',
          'markup.bold markup.italic string',
          'markup.italic markup.bold string',
          'markup.quote markup.bold string',
        ],
        settings: { fontStyle: 'bold italic', foreground: p.violet },
      },
      {
        name: 'Markup - Underline',
        scope: ['markup.underline'],
        settings: { fontStyle: 'underline', foreground: p.accent },
      },
      {
        name: 'Markdown - Blockquote',
        scope: ['markup.quote punctuation.definition.blockquote.markdown'],
        settings: { foreground: p.accent },
      },
      {
        name: 'Markup - Quote',
        scope: ['markup.quote'],
        settings: { fontStyle: 'italic', foreground: p.violet },
      },
      {
        name: 'Markdown - Link',
        scope: ['string.other.link.title.markdown'],
        settings: { foreground: p.accent },
      },
      {
        name: 'Markdown - Link Description',
        scope: ['string.other.link.description.title.markdown'],
        settings: { foreground: p.violet },
      },
      {
        name: 'Markdown - Link Anchor',
        scope: ['constant.other.reference.link.markdown'],
        settings: { foreground: p.accent },
      },
      {
        name: 'Markup - Raw Block',
        scope: ['markup.raw.block'],
        settings: { foreground: p.violet },
      },
    ],
  };
}
